### ISSUE TITLE
support for generator functions and async functions

### ISSUE THREAD

**Issue by ORESoftware** [tunnckoCore/parse-function#12]
Loving this lib so far, but it appears that it is not currently configured to parse generator functions and async functions

``` js
function*
```

and async functions

``` js
async function(){

}
```

can this be confirmed and do you plan to update it if so? thanks!

**Comment by tunnckoCore** [comment]
Which version you use? It should work for generator functions (im not sure) because v2.3.x is on top acorn.

I'll check and add tests ASAP, or you can PR some tests :)

**Comment by tunnckoCore** [comment]
@ORESoftware use `v2.3.x` if you need advanced things - it have full support for what acorn can do. The other versions not uses `acorn` so things like that are hard and not handled.

If you just need to get arguments/parameters use `v2.0.x` it is much faster.

**Comment by ORESoftware** [comment]
Thanks yeah I need to parse ES7 functions - async functions and generators\*  - it looks like you use / acorn uses ES7 parsing by default. I am not concerned about speed- I just need reliability for this

**Comment by tunnckoCore** [comment]
@ORESoftware yea i forced ES7, acorn's default is ES6 (meaning acorn ecmaScript default is 6, parse-functions force it to 7) :)

Thanks using it!

**Comment by ORESoftware** [comment]
yeah it's working for me so far
