### ISSUE TITLE
5.2.0 has no dist folder

### ISSUE THREAD

**Issue by Alex-D** [tunnckoCore/parse-function#125]
Seems you failed at publishing dist folder in 5.2.0 :-°

**Comment by tunnckoCore** [comment]
ohhhhh, daamnn, always forget. I will update the boilerplate and scripts soon so such things won't be a problem anymore.

so.. yea will realise 5.2.1 later today

**Comment by tunnckoCore** [comment]
release*

**Comment by Alex-D** [comment]
(you can edit a message if you want fix it ;))

**Comment by tunnckoCore** [comment]
From the phone, no (it depends).
