### ISSUE TITLE
Class methods

### ISSUE THREAD

**Issue by rkaw92** [tunnckoCore/parse-function#15]
Parsing class methods seems to yield empty bodies, anonymous names and empty arg lists.

Example:

``` js
'use strict';

var parseFunction = require('parse-function');

class EqualityChecker {
    isEqual(a, b) {
        return a === b;
    }
}

var checker = new EqualityChecker();
console.log('Prototype:', parseFunction(EqualityChecker.prototype.isEqual));
console.log('Instance:', parseFunction(checker.isEqual));
```

Both console.logs will print `{ name: 'anonymous', args: [], params: '', body: '' }`.

I suspect it is because `.toString()` on methods returns the exact representation from the code, from the first to the last token, so in our case (tabs originally in the string):

``` js
isEqual(a, b) {
                return a === b;
        }
```

The same problem occurs with this compacted ES6 "function-less" notation:

``` js
parseFunction({
    isEqual(a, b) {
        return a === b;
    }
}.isEqual)
```

**Comment by tunnckoCore** [comment]
Hey, very thanks! I'll look into it, I think we just should look more on acorn ast.

**Comment by tunnckoCore** [comment]
I'm starting to think it may be `acorn` issue.

``` js
acorn.parse(EqualityChecker.prototype.isEqual.toString(), {ecmaVersion: 7})
```

throws a syntax error. Or maybe this is the reason why `acorn.parse_dammit` exists. And that's why I using it, because such cases. I'm looking on ast that `parse_dammit` returns for that, may need more `if`s in the `walk` :)

**Comment by tunnckoCore** [comment]
There are few ways:
1. detect if result of `toString()` begins with `function` or at least the letter `f` and if not prepend it
2. add `if` in the walk to listen to `CallExpression`

Second feels kinda wrong to me and I'm thinking it would mess the things more than it solve them.

**Comment by tunnckoCore** [comment]
What you think about the fix?

edit: Ooops, labels should stay.

**Comment by rkaw92** [comment]
As much as I am bewildered by the choice of substring check mechanism ([0] and [1] - I assume it's for performance reasons), this is exactly the workaround that I did in my code:

``` js
let functionString = methodFunction.toString();
if (functionString.slice(0, 8) !== 'function') {
    functionString = 'function ' + functionString;
}
```

I agree that it is the sane thing to do. Checking for function calls is probably best left alone - there is another npm module for that (extracts call parameters), and it may be wise not to expand into that field.

**Comment by tunnckoCore** [comment]
Yea.

> extracts call parameters

You can try http://npm.im/function-arguments, it works for regular, generator and arrow functions. If you need support only for regular functions can use Sindre's `fn-args`, it's lighter and probably faster.

It would be better choice to use one of them if you only need getting arguments.

**Comment by tunnckoCore** [comment]
Oh sorry, i forget to publish. I doing it now :) `v2.3.2`
