### ISSUE TITLE
ES6 features

### ISSUE THREAD

**Issue by skamenetskiy** [tunnckoCore/parse-function#18]
Hey, I'm trying to use some ES6 standards, which should be supported according to the readme.

``` javascript
const parseFunction = require('parse-function');

function a({
    a = null,
    b = null,
    c = null
}) {
    console.log('a', a, b, c);
}

const b = ({a=null, b=null, c}, d, {e=null, m=12} = {}, f) => {
    console.log('b', a, b, c);
};

const c = () => {
    console.log('c');
};

function d() {
    console.log('d');
}

function e(a) {
    console.log('e', a);
}

console.log(parseFunction(a));
console.log(parseFunction(b));
console.log(parseFunction(c));
console.log(parseFunction(d));
console.log(parseFunction(e));
```

**Comment by rkaw92** [comment]
Hi, I'm not sure the readme promises to support _object destructuring_. It says this:
`full support of es6 arrow functions and es6 default params`

And indeed, the following seems to work (though it does not "save" the default value anywhere):

``` js
const f = (a = 1) => {
    console.log('f', a);
}
console.log(parseFunction(f));
```

**Comment by tunnckoCore** [comment]
Yep. Need more work, it is just thin layer on top of acorn ast, so PRs welcome. Just need more `if`s ;d

**Comment by tunnckoCore** [comment]
Also, I'm not sure what should be the response for your examples, @skamenetskiy.

**Comment by tunnckoCore** [comment]
@rkaw92, @skamenetskiy hi there.

Last few weeks i'm digging more and more on parsers, bundling and etc stuff and now i'm lookin into `babylon` ast, so I can improve that things.

```js
const babylon = require('babylon')
const ast = babylon.parse(`function myFn (a = {aaa: {bea: 'c'}}, b = 123, ...rest) {
  return [a + b, rest]
}`)
console.log(ast.program.body[0].params)
// if AssignmentPattern then we will just get `.left` 
```

**Comment by tunnckoCore** [comment]
Actually, no, won't do anything. It totally not make any sense to have support for destructing. Default arguments make sense, because they have _names_ which you can point to.

That library has one main purpose, stay as small and simple as possible. Super useful for dependency injection and etc stuff. If the user won't the cost of full using source code parsers like `acorn` and `babylon`, then so they can use [function-arguments](https://github.com/tunnckoCore/function-arguments) if their use case is DI.

**Comment by tunnckoCore** [comment]
So this is invalid for me

```js
// not ok
function a({
    a = null,
    b = null,
    c = null
}) {
    console.log('a', a, b, c);
}
```
and won't be supported.

As about mixing `default arguments` and `destructing`...
Consider the following (edited from your snippets)

```js
const bear = ({a=null, b=null, c}, def = 33, {e=null, m=12} = {}, foo, qux, ...rest) => {
    console.log('b', a, b, c)
}

const parseFunction = require('parse-function')
const parsed = parseFunction(bear)

console.log(parsed.args) // => [false, 'def', false, 'foo', 'qux', 'rest']
console.log(parsed.defaults) // => {def: 33, foo: undefined, qux: undefined, rest: undefined}
```

I'm going to close this one and update the package. Possibly will publish v3 using `babylon` or latest `acorn`

**Comment by tunnckoCore** [comment]
@skamenetskiy v4 is on the master. You could do what you want now, because we have plugins api and relies on Babylon by default (but can be switched). :) Feedback welcome :)
