### ISSUE TITLE
V5.3.2 Error: Cannot find module './utils'

### ISSUE THREAD

**Issue by sky172839465** [tunnckoCore/parse-function#202]
In `@5.3.2`  `cjs/index.js` throws the following error:
```
Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (xxx/node_modules/parse-function/dist/cjs/index.js:1:731)
```

Seems doesn't bundle utils.js into index.js

**Comment by Super-Eric** [comment]
Thank you for raising the issue ;-) I have to work around this one by using:
npm install parse-function@5.3.1

As the library codeceptjs has this one as the dependency ;-)

**Comment by tunnckoCore** [comment]
Sorry, for the delay, it's hard to handle so many notifications and easy to miss.

This isn't the home for the package for a long time. Before few months I moved it to couple places. Now finally it's on my monorepo where I'm moving everything and is pretty stable.

Please install 5.4+.

https://github.com/tunnckoCore/opensource/

For easier access to my or other repos actual home, you can use https://ghub.now.sh service.

<blockquote><img src="https://avatars2.githubusercontent.com/u/5038030?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/tunnckoCore/opensource">tunnckoCore/opensource</a></strong></div><div>Delivering delightful digital solutions. JavaScript Open Source Monorepo, semantically versioned following @conventional-commits. Fully powered by Jest, @Babel TypeScript, @Airbnb @ESLint + @Pretti...</div></blockquote>
<blockquote><div><strong><a href="https://ghub.now.sh/">GHUB NOW - ghub.now.sh</a></strong></div></blockquote>

**Comment by Super-Eric** [comment]
Thank you very much @tunnckoCore. I have installed 5.4.3 and it is working great for me now.

**Comment by tunnckoCore** [comment]
Great to hear, you can star and "Watch Releases" for the repo. :)

And also heck the upcoming v6 https://github.com/tunnckoCore/opensource/pull/72
