### ISSUE TITLE
improve code climate shits

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/parse-function#26]

**Comment by tunnckoCore** [comment]
https://github.com/tunnckoCore/parse-function/commit/957e9945124fd1d52db7e5a22f6f6809cb6b5a63 and https://github.com/tunnckoCore/parse-function/commit/bde2cfd4f225a0a38f34b088e963e12107ac8e99

**Comment by the1mills** [comment]
❤️ ✨

**Comment by tunnckoCore** [comment]
@the1mills v4 is just published on npm ;p feedback welcome.

**Comment by the1mills** [comment]
Will do, is there a changelog!

**Comment by tunnckoCore** [comment]
Yea, at the root of the repository. And the readme is pretty big. Let me know if something is not clear.
