### ISSUE TITLE
Low-prio: failing when something after CLOSE_CURLY

### ISSUE THREAD

**Issue by tunnckoCore** [tunnckoCore/parse-function#3]
e.g.

``` js
var parseFunction = require('parse-function')
var fnStr = 'function (a) {return a}; var b = 1'
var data = parseFunction(fnStr)

console.log(data.body) // => 'return a}; var b = ' instead of 'return a'
```

resolved locally

**Comment by tunnckoCore** [comment]
Should we handle this? This lib isn't meant to do that, in my opinion. It is meant to be passed with an actual function, so such scenario is rare case.

**Comment by ericmorand** [comment]
I tend to agree that this lib should not handle that case which is _not_ a function.

**Comment by tunnckoCore** [comment]
Okey, closing. If anyone has some thoughts then to feel free to share.
