### ISSUE TITLE
Suggest `args` be called `params` and `params` be called `paramsString` or something

### ISSUE THREAD

**Issue by keenahn** [tunnckoCore/parse-function#33]
Based on the widely accepted definition, both of these describe formal parameters and neither describe arguments, so should move away from using `args`.

https://en.wikipedia.org/wiki/Parameter_(computer_programming)

**Comment by tunnckoCore** [comment]
Probably good point, but that would be breaking change that i don't want, currently. Maybe can be delayed to next major version bump.

**Comment by tunnckoCore** [comment]
But when i think it, even with major it will be confusing, because the old `params` will be the old `args` and `args` will be removed, so..

**Comment by tunnckoCore** [comment]
Sorry, but won't do it. These are stylistic and semantic things + above comment, even with major it would be confusing and totally reversing thing.

I'm going to publish new release, but won't update that thing, will require just boilerplate updates and requires node v6.
