### ISSUE TITLE
Strange parser error when an `if` statement is at the top of an async arrow function

### ISSUE THREAD

**Issue by TooTallNate** [tunnckoCore/parse-function#61]
Apologies if this is not a bug in `parse-function` itself, but I've tried this with all 3 recommended AST parsers and they all exhibit the same problem.

A parser error is thrown when an async arrow function has an `if` statement at the top. Ex:

```
$ cat t.js
const parser = require('parse-function')()

const fn = async (req, res) => {
  if (req) {}
}

console.log(parser.parse(fn));

$ node t
/test/node_modules/parse-function/node_modules/babylon/lib/index.js:812
    throw err;
    ^

SyntaxError: Unexpected token, expected { (1:19)
```

Strangely, the same error is thrown _even if the `if` statement is commented out!_

```
$ cat t.js
const parser = require('parse-function')()

const fn = async (req, res) => {
  //if (req) {}
}

console.log(parser.parse(fn));

$ node t
/test/node_modules/parse-function/node_modules/babylon/lib/index.js:812
    throw err;
    ^

SyntaxError: Unexpected token, expected { (1:19)
```

Now, it works if I remove the `if` statement:

```
$ cat t.js
const parser = require('parse-function')()

const fn = async (req, res) => {
}

console.log(parser.parse(fn));

$ node t
{ name: null,
  body: '\n',
  args: [ 'req', 'res' ],
  params: 'req, res' }
```

It also works if I change it to a regular async function instead of an arrow function:

```
$ cat t.js
const parser = require('parse-function')()

const fn = async function (req, res) {
  if (req) {}
}

console.log(parser.parse(fn));

$ node t
{ name: null,
  body: '\n  if (req) {}\n',
  args: [ 'req', 'res' ],
  params: 'req, res' }
```

So, strange behavior to say the least. Or maybe I'm doing something dumb. V8 at least has no problem parsing any of these versions. Thanks in advance for any support!

**Comment by tunnckoCore** [comment]
Hey there! :wave: Thanks for the report, it sounds me like problem here.
I bet it's because of this here [src/index.js#L106-L113](https://github.com/tunnckoCore/parse-function/blob/master/src/index.js#L106-L113).

The idea about that `if` there, is if we have passed async method, then we should wrap it in object, so the parser can parse it correctly.

Can you try to add this check too and try again if it works

```js
const isAsyncArrow = result.value.startsWith('async')

if (!(isFunction || isAsyncFn || isAsyncArrow) && isMethod) {
  result.value = `{ ${result.value} }`
}
```

Another reason and probably limitation is that we use `babylon.parseExpression` by default [here](https://github.com/tunnckoCore/parse-function/blob/e832765ad89c1596af31af8a822b2cb5772786f7/src/lib/utils.js#L87), but as i remember, it was intentional.

**Comment by TooTallNate** [comment]
@charlike The patch works for me 👍 Thank you for the quick turnaround on that!

**Comment by tunnckoCore** [comment]
Sweeeet! :D I love myself sometimes for such fast responses with good end :)

PR is welcome, otherwise i can push patch in coming days. Let me know if you need some help on contributing.

**Comment by TooTallNate** [comment]
Well it's your patch. I look forward to the upcoming release 👍

**Comment by the1mills** [comment]
🐯🐯🐯🐯🐯🐯🐯🐯

**Comment by tunnckoCore** [comment]
@the1mills what? :joy_cat: haha

@TooTallNate actually, yea, but it's not a problem for me. Go pr if you need it more soon.

**Comment by TooTallNate** [comment]
Please see https://github.com/tunnckoCore/parse-function/pull/63.

@charlike P.S. I'd be happy to be added as a contributor, if this module has become a burden on your time.

**Comment by tunnckoCore** [comment]
heya, just seen your comment here.

> if this module has become a burden on your time

no, it's not, just i'm in period of switching ISP providers and following through smartphone is hard, haha.

i'll add you once I get stability and time, no problem :)
